### ISSUE TITLE
Contextual menu pattern design and spec

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-dashboard-theme-design#19]
E.g. Juju kebab icon in machine view

**Comment by anthonydillon** [comment]
As it stands, Juju won't be joining the dashboard theme family. The kebab
menu is used in machine view which will be a local resource to Juju GUI.

**Comment by yaili** [comment]
If I remember correctly, during the workshop we mentioned this pattern could be useful on MAAS and Landscape. Remember @kwm14 @MariaVrachni ?

**Comment by kwm14** [comment]
@yaili yes I remember that we agreed it would be useful and consistent to use the same pattern across our Cloud products.

**Comment by MariaVrachni** [comment]
@yaili I need a reminder. Can you give an example of where or how it would be used?

**Comment by yaili** [comment]
@MariaVrachni there aren't any instances of it in Landscape that I can think of, but could be useful pattern for small screen layouts. I don't know about MAAS.

**Comment by MariaVrachni** [comment]
@yaili I remember our conversation now: A menu whose content changes based on where you are in the app. 
The 'Actions' bulk button is an example in MAAS, which is in the same position across the application but has different contents depending on the page the user is in. It is certainly worth exploring on how to improve and adopt in the rest of the cloud products.

**Comment by yaili** [comment]
In specs now: https://github.com/ubuntudesign/vanilla-dashboard-theme-design/tree/master/Contextual%20menu

**Comment by MariaVrachni** [comment]
@yaili not sure it is not too late for an enhancement proposal.

When we have a long list of actions in the menu, it is good to use a horizontal line to separate and group them, so that the user can scan them easily. Also, the line helps separate destructive actions, such as delete, remove, destroy etc. I think it would be good to have this as part of the pattern.

**Comment by yaili** [comment]
@MariaVrachni the pattern allows for this, it's not the in the png image but it's in the markdown detailed spec file 👍

**Comment by MariaVrachni** [comment]
@yaili That's great! 

There is one more issue. Mark commented on single actions being hidden in the menu (while they could be exposed directly on the UI) and I agree with his point. I propose we evolve the UX design spec of this component so that it is introduced only after a specific number of items. 

I filed a bug that can be found here: https://github.com/ubuntudesign/vanilla-dashboard-theme-design/issues/30
