### ISSUE TITLE
Finalise tabs patterns design

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-dashboard-theme-design#6]
**In our kick-off meeting we discussed which tabs should go into the Dashboard theme, these questions were raised when reviewing tabs currently in MAAS:**

- Scaling design (for many tab headers)
- Review highlight colour
- How does it work in mobile/responsive?

Currently both MAAS and Landscape we use similar style tabs, but in Vanilla we have a tab (breadcrumb) pattern which is different and one we could potentially adopt?

### Landscape tabs
![tabs_landscape](https://cloud.githubusercontent.com/assets/17748020/20399457/fc7afeca-ace8-11e6-8116-cdda187842d8.jpg)

### MAAS tabs
![tabs_maas](https://cloud.githubusercontent.com/assets/17748020/20399429/e0e66e7e-ace8-11e6-9ec1-6c7287de7a94.jpg)

### Vanilla tabs (breadcrumb)
![tabs_vanilla](https://cloud.githubusercontent.com/assets/17748020/20399488/1cdd0276-ace9-11e6-94e5-0a8f377262bd.jpg)

@spencerbygraves has been exploring tabs so it would be good to make these consistent, he has applied it to Juju and I took his styling and applied to MAAS which can be seen below. It is scalable and works for mobile the only decision that needs to be made is on the highlight colour?

### MAAS tabs proposal
![tabs_maas_proposal](https://cloud.githubusercontent.com/assets/17748020/20399735/0ae50e64-acea-11e6-9d01-9af9d656e38d.jpg)

**Comment by yaili** [comment]
Thanks, @kwm14 

The Vanilla tabs are not tabs, they're just breadcrumbs :)

**Comment by jamiedawsonyoung** [comment]
Hey @kwm14 :-)

Do you or @spencerbygraves have an example of it working in a narrow screen? (apologies if I'm being stupid!) I also thought something we had to tackle for convergence might be interesting. 

We have 'tabs' too (we call them section headers as we have tabs on the browser) we have a pattern where we deal with an overflow of these as well as in something called the toolbar (which is essentially a list of icons). Only reason I mention it was because we had quite a nice interaction for it and I don't know if it would be helpful / possible here.

I've linked to a film of a prototype @faooful helped me make for this. It explains it better than I can :-) https://www.dropbox.com/s/1upu25oeqfx7vpe/header-toolbar-overflow-3.mov?dl=0

**Comment by spencerbygraves** [comment]
We have tabs on the small screen version of the GUI, but this is only 2 items for services and machines. I styled the versions on the docs navigation as tabs (before realising they're not actually tabs) and that had 3/4 short items.

So, we'll need a solution, thanks for sharing.

**Comment by yaili** [comment]
Spec: https://github.com/ubuntudesign/vanilla-dashboard-theme-design/tree/master/Tabs
